apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: geode-server
    chart: geode-0.1.0
    heritage: Tiller
    release: geode
  name: geode-server
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: geode-server
      release: geode
  serviceName: ""
  template:
    metadata:
      labels:
        app: geode-server
        release: geode
    spec:
      containers:
      - command:
        - sh
        - -c
        - |
          gfsh start server --name=${HOSTNAME} --dir=/data --J=-Dgemfire.locator-wait-time=100 \
          --locators=geode[10334] \
          --max-heap=256m --hostname-for-clients=$(hostname -i) \
          --bind-address=$(hostname -i) --jmx-manager-hostname-for-clients=$(hostname -i) \
          --J=-Dgemfire.log-file=/var/log/server.log && \
          tail -f /var/log/server.log
        image: apachegeode/geode:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              cat /data/vf.gf.server.pid | xargs ps
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: geode
        ports:
        - containerPort: 40404
          name: server
          protocol: TCP
        - containerPort: 1099
          name: jmx
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              cat /data/vf.gf.server.pid | xargs ps
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: varlog
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
