apiVersion: v1
kind: Service
metadata:
  name: locator-external
  namespace: geode
spec:
  ports:
    - port: 7070
      name: pulse-port
  type: LoadBalancer
  selector:
    app: locator
---
apiVersion: v1
kind: Service
metadata:
  name: locator-internal
  namespace: geode
spec:
  ports:
    - port: 10334
      name: locator-port
  clusterIP: None
  selector:
    app: locator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: locator
  namespace: geode
spec:
  serviceName: "locator-service"
  selector:
    matchLabels:
      app: locator
  replicas: 2
  template:
    metadata:
      labels:
        app: locator
    spec:
      containers:
        - name: locator
          image: gcr.io/solstice-api-junkyard/geode
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              gfsh -e "start locator --name=${HOSTNAME} --dir=/data \
              --locators=locator-internal[10334] \
              --max-heap=128m --hostname-for-clients=$(hostname -i) \
              --bind-address=$(hostname -i) --jmx-manager-hostname-for-clients=$(hostname -i) \
              --http-service-port=7070 \
              --J=-Dgemfire.log-file=/var/log/locator.log" \
              -e "configure pdx --read-serialized=true --disk-store=DEFAULT" && \
              tail -f /var/log/locator.log
          ports:
            - containerPort: 10334
              name: locator
            - containerPort: 1099
              name: jmx
            - containerPort: 7070
              name: http
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  cat /data/vf.gf.locator.pid | xargs ps
            initialDelaySeconds: 60
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  cat /data/vf.gf.locator.pid | xargs ps
            initialDelaySeconds: 60
            periodSeconds: 5
      volumes:
        - name: varlog
          emptyDir: {}
