apiVersion: v1
kind: Service
metadata:
  name: locator-service
  namespace: geode
spec:
  ports:
    - port: 7070
      name: pulse-port
  type: LoadBalancer
  selector:
    app: locator
---
apiVersion: v1
kind: Service
metadata:
  name: locator
  namespace: geode
spec:
  ports:
    - port: 10334
      name: locator-port
  clusterIP: None
  selector:
    app: locator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: locator
  namespace: geode
spec:
  serviceName: "locator-service"
  selector:
    matchLabels:
      app: locator
  replicas: 2
  template:
    metadata:
      labels:
        app: locator
    spec:
      containers:
        - name: locator
          image: gcr.io/solstice-api-junkyard/geode
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              sh /geode-config/genenete-properties.sh locator && \
              gfsh -e "start locator \
                  --name=${HOSTNAME} \
                  --dir=/data \
                  --port=10334 \
                  --properties-file=/root/geode.properties && \
                  --J=-Dgemfire.log-file=/var/log/locator.log" \
                  -e "configure pdx --read-serialized=true --disk-store=DEFAULT" && \
              tail -f /var/log/locator.log
          ports:
            - containerPort: 10334
              name: locator
            - containerPort: 1099
              name: jmx
            - containerPort: 7070
              name: http
          volumeMounts:
            - name: geode-config
              mountPath: /geode-config
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  cat /data/vf.gf.locator.pid | xargs ps
            initialDelaySeconds: 60
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  cat /data/vf.gf.locator.pid | xargs ps
            initialDelaySeconds: 60
            periodSeconds: 5
      volumes:
        - name: varlog
          emptyDir: {}
        - name: geode-config
          configMap:
            name: geode-config
