apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: geode
spec:
  ports:
    - port: 40404
      name: server
  clusterIP: None
  selector:
    app: server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
  namespace: geode
spec:
  selector:
    matchLabels:
      app: server
  serviceName: "server"
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: gcr.io/solstice-api/geode
          command:
            - sh
            - -c
            - |
              gfsh start server \
                  --name=${HOSTNAME} \
                  --dir=/data \
                  --server-port=40404 \
              while true; do
                sleep 2
              done
          ports:
            - containerPort: 40404
              name: server
            - containerPort: 1099
              name: jmx
          volumeMounts:
            - name: geode-data
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  PID=$(cat /data/vf.gf.server.pid) && [ -x /proc/${PID} ]
            initialDelaySeconds: 20
            periodSeconds: 1
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    gfsh stop locator --dir=/data
      initContainers:
        - name: wait-for-locator
          image: busybox
          command:
            - sh
            - -c
            - |
              until nslookup locator-headless-internal; do
                echo "Waiting for locator"
                sleep 2
              done;
      volumes:
        - name: geode-data
          persistentVolumeClaim:
            claimName: geode-data
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - server
              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
    - metadata:
        name: geode-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: server
  namespace: geode
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: server